#!/usr/bin/env tsx
/**
 * generate-recipe-md.ts
 * Generates Markdown reflections from canonical JSON recipe definitions.
 */
import { readFileSync, existsSync, mkdirSync, writeFileSync, readdirSync } from "fs";
import { resolve, join } from "path";

const RECIPES_DIR = resolve("meta/governance/recipes");
const OUTPUT_DIR = resolve("project-governance/recipes");

interface Recipe {
  id: string;
  version: string;
  category: string;
  title: string;
  purpose: string;
  prerequisites: string[];
  steps: Array<{ id: string; description: string; command?: string; validation?: string }>;
  recovery?: { auto_recoverable: boolean; steps: string[] };
  rollback?: { required: boolean; snapshot_before: boolean; steps: string[] };
  validation: string[];
  estimated_duration_minutes?: number;
  risk_level?: string;
}

function loadRecipes(): Recipe[] {
  if (!existsSync(RECIPES_DIR)) return [];
  const files = readdirSync(RECIPES_DIR).filter((f: string) => f.endsWith(".json") && f !== "recipe.schema.json");
  const recipes: Recipe[] = [];
  for (const f of files) {
    try {
      const data = JSON.parse(readFileSync(join(RECIPES_DIR, f), "utf-8"));
      recipes.push(data);
    } catch { /* skip invalid */ }
  }
  return recipes;
}

function generateMarkdown(recipe: Recipe): string {
  const lines: string[] = [];
  lines.push(`# ${recipe.title}`);
  lines.push("");
  lines.push(`> **Recipe ID:** \`${recipe.id}\`  `);
  lines.push(`> **Version:** ${recipe.version}  `);
  lines.push(`> **Category:** ${recipe.category}  `);
  lines.push(`> **Risk Level:** ${recipe.risk_level || "unknown"}  `);
  lines.push(`> **Estimated Duration:** ${recipe.estimated_duration_minutes || "unknown"} minutes  `);
  lines.push("");
  lines.push("## Purpose");
  lines.push("");
  lines.push(recipe.purpose);
  lines.push("");

  lines.push("## Prerequisites");
  lines.push("");
  for (const p of recipe.prerequisites) {
    lines.push(`- [ ] ${p}`);
  }
  lines.push("");

  lines.push("## Steps");
  lines.push("");
  for (let i = 0; i < recipe.steps.length; i++) {
    const step = recipe.steps[i];
    lines.push(`${i + 1}. **${step.id}** — ${step.description}`);
    if (step.command) {
      lines.push(`   \`\`\`bash`);
      lines.push(`   ${step.command}`);
      lines.push(`   \`\`\``);
    }
    if (step.validation) {
      lines.push(`   *Validation:* ${step.validation}`);
    }
    lines.push("");
  }

  if (recipe.recovery) {
    lines.push("## Recovery");
    lines.push("");
    lines.push(`Auto-recoverable: ${recipe.recovery.auto_recoverable ? "Yes" : "No"}`);
    for (const step of recipe.recovery.steps) {
      lines.push(`- ${step}`);
    }
    lines.push("");
  }

  if (recipe.rollback && recipe.rollback.required) {
    lines.push("## Rollback");
    lines.push("");
    lines.push(`Snapshot required: ${recipe.rollback.snapshot_before ? "Yes" : "No"}`);
    for (const step of recipe.rollback.steps) {
      lines.push(`- ${step}`);
    }
    lines.push("");
  }

  lines.push("## Validation");
  lines.push("");
  for (const v of recipe.validation) {
    lines.push(`- [ ] ${v}`);
  }
  lines.push("");
  lines.push("---");
  lines.push("*Generated from canonical JSON recipe definition.*");
  lines.push("*Do not edit this file directly. Edit the JSON source and regenerate.*");

  return lines.join("\n");
}

export function generateAllReflections(): { generated: string[]; count: number } {
  const recipes = loadRecipes();
  if (!existsSync(OUTPUT_DIR)) mkdirSync(OUTPUT_DIR, { recursive: true });

  const generated: string[] = [];
  for (const recipe of recipes) {
    const md = generateMarkdown(recipe);
    const path = join(OUTPUT_DIR, `${recipe.id}.recipe.md`);
    writeFileSync(path, md);
    generated.push(path);
  }

  return { generated, count: recipes.length };
}

export { loadRecipes, generateMarkdown };

// CLI
if (import.meta.url === `file://${process.argv[1]}`) {
  const result = generateAllReflections();
  console.log(`Generated ${result.count} recipe reflection(s):`);
  for (const path of result.generated) {
    console.log(`  ${path}`);
  }
}
